@port = {{$dotenv PORT}}
@baseUrl = http://localhost:{{port}}


### Get track by id
GET {{baseUrl}}/api/tracks/comples


### Get track by id
GET {{baseUrl}}/api/tracks/Kartoffel

### Get tracks
GET {{baseUrl}}/api/tracks